openapi: 3.0.0
info:
  title: Entertainment Web
  description: Entertainment web API
  version: 0.1.9

servers:
  - url: http://localhost:3000/api
    description: local server
  - url: https://entertainment-web-2qzi.onrender.com/api
    description: render server
  - url: https://long-pink-pelican-cap.cyclic.app/api
    description: cyclic server
paths:
  /films:
    get:
      tags:
        - Films
      responses:
        "200":
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /auth/signup:
    post:
      tags:
        - Authorisation
      requestBody:
        description: create new user
        required: true
        content:
          multipart/form-data:
            schema:
              type: "object"
              properties:
                email:
                  type: string
                password:
                  type: string
                avatar:
                  type: string
                  format: binary
      responses:
        "201":
          description: new user create successfully
  /users:
    get:
      tags:
        - Users
      responses:
        "200":
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: array
                email:
                  type: string
                password:
                  type: string
                avatar:
                  type: string
                  format: binary
  /user/login:
    post:
      tags:
        - Login
      requestBody:
        description: user authorization
        required: true
        content:
          application/json:
            schema:
              type: "object"
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: login successfully
  /user:
    get:
      tags:
        - Userwe
      description: Get information about a logged-in user
      security:
        - bearerAuth: []
      responses:
        200:
          description: Successfully retrieved user information
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                  avatar:
                    type: string
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Unauthorized"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Internal Server Error"
