openapi: 3.0.0
info:
  title: Entertainment Web
  description: Entertainment web API
  version: 0.1.9

servers:
  - url: http://localhost:3000/api
    description: local server
  - url: https://entertainment-web-u5fj.onrender.com/api
    description: render server
paths:
  /films:
    get:
      tags:
        - films
      responses:
        "200":
          description: Successfully fetched
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
